# Generated by Django 4.1.7 on 2023-03-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0004_typesection_sectionyoga_sectionfighter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_index=True, max_length=20, verbose_name='Рабочее время')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Номер телефона')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления клиента')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных')),
                ('payed_date', models.DateField(verbose_name='Дата оплаты')),
                ('payed_status', models.CharField(max_length=255, verbose_name='Статус оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.profile', verbose_name='Тренер')),
                ('work_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.alltime', verbose_name='Рабочие часы')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент')),
                ('visit_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.worktime', verbose_name='Время посещения тренировки с тренером')),
            ],
        ),
        migrations.CreateModel(
            name='CoachForClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.profile', verbose_name='Тренер')),
            ],
        ),
    ]
