# Generated by Django 4.1.7 on 2023-03-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_coachforclient_coach_alter_worktime_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='payed_date',
            field=models.DateField(choices=[('paid', 'Оплачен'), ('notpaid', 'Не оплачен')], default='notpaid', verbose_name='Дата оплаты'),
        ),
    ]
