# Generated by Django 4.1.7 on 2023-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_clients_payed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='payed_date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='payed_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('notpaid', 'Не оплачен'), ('pause', 'Пауза'), ('first', 'Первая тренировка'), ('part', 'Частичная оплата')], default='notpaid', max_length=255, verbose_name='Статус оплаты'),
        ),
    ]
