# Generated by Django 4.1.7 on 2023-03-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_clients_payed_date_alter_clients_payed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachforclient',
            name='visit_time',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.worktime', verbose_name='Время посещения тренировки с тренером'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clients',
            name='payed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.DeleteModel(
            name='VisitTime',
        ),
    ]
