# Generated by Django 4.1.7 on 2023-03-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_coachforclient_visit_time_alter_clients_payed_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=255, verbose_name='Возрастная группа')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='День')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Место тренировки')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='Тип секции')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('new', 'Новый клиент'), ('refusal', 'Отказ'), ('recorded', 'Записан')], default='new', max_length=255, verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='payed_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('notpaid', 'Не оплачен'), ('pause', 'Пауза'), ('first', 'Первая тренировка'), ('part', 'Частичная оплата'), ('one_paid', 'Поразово'), ('this_month', 'Долг свыше месяца')], default='notpaid', max_length=255, verbose_name='Статус оплаты'),
        ),
        migrations.CreateModel(
            name='UserSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_section', models.CharField(blank=True, choices=[('yoga', 'йога'), ('martialArts', 'единоборства')], default=None, max_length=255, null=True, verbose_name='Тип секции')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.age', verbose_name='Возрастная группа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.days', verbose_name='День посещения')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.location', verbose_name='Локация')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.section', verbose_name='Секция')),
                ('visit_time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.worktime', verbose_name='Время посещения тренировки с тренером')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients')),
            ],
        ),
    ]
