# Generated by Django 4.1.7 on 2023-03-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_age_days_location_section_clients_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersection',
            name='type_section',
        ),
    ]
