# Generated by Django 4.1.7 on 2023-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_usersection_type_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=255, verbose_name='Название группы')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
    ]
