# Generated by Django 4.1.7 on 2023-03-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_grouptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000, verbose_name='Локации которые были выбраны')),
                ('visit_time', models.CharField(max_length=1000, verbose_name='Время которое было выбрано')),
                ('section', models.CharField(max_length=1000, verbose_name='Секции которое были выбраны')),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='payed_status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('notpaid', 'Не оплачен'), ('pause', 'Пауза'), ('first', 'Первая тренировка'), ('part', 'Частичная оплата'), ('one_paid', 'Поразово'), ('this_month', 'Долг свыше месяца'), ('new_client', 'Новый клиент')], default='notpaid', max_length=255, verbose_name='Статус оплаты'),
        ),
    ]
