# Generated by Django 4.1.7 on 2023-03-29 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_formclient_alter_clients_payed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formclient',
            name='age',
            field=models.CharField(default=True, max_length=100, verbose_name='Возрастная категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formclient',
            name='client',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formclient',
            name='visit_day',
            field=models.CharField(default=1, max_length=1000, verbose_name='Дни которое было выбрано'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formclient',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Локации которые были выбраны'),
        ),
        migrations.AlterField(
            model_name='formclient',
            name='section',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Секции которое были выбраны'),
        ),
        migrations.AlterField(
            model_name='formclient',
            name='visit_time',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Время которое было выбрано'),
        ),
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Локации которые были выбраны')),
                ('section', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Секции которое были выбраны')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients')),
            ],
        ),
    ]
