# Generated by Django 4.1.7 on 2023-04-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_clients_status_coach_clients_status_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('new', 'Новый клиент'), ('refusal', 'Отказ'), ('recorded', 'Записан')], default='new', max_length=255, verbose_name='Статус клиента'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status_coach',
            field=models.CharField(choices=[('not_check', 'Не проверен'), ('checked_upload', 'Проверен, записан'), ('checked_closed', 'Проверен, отказ'), ('not_registered', 'Не закреплен')], default='not_check', max_length=255, verbose_name='Cтатус проверки тренера'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status_operator',
            field=models.CharField(choices=[('not_check', 'Не проверен'), ('checked_upload', 'Проверен, записан'), ('checked_closed', 'Проверен, отказ'), ('not_registered', 'Не закреплен')], default='not_check', max_length=255, verbose_name='Статус оператора'),
        ),
    ]
