# Generated by Django 4.1.7 on 2023-04-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_clients_status_alter_clients_status_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status_coach',
            field=models.CharField(choices=[('not_check', 'Не проверен'), ('checked_upload', 'Проверен, записан'), ('checked_closed', 'Проверен, отказ')], default='not_check', max_length=255, verbose_name='Статус проверки тренера'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status_operator',
            field=models.CharField(choices=[('not_check', 'Не проверен'), ('checked_upload', 'Проверен, записан'), ('checked_closed', 'Проверен, отказ')], default='not_check', max_length=255, verbose_name='Статус оператора'),
        ),
    ]
