# Generated by Django 4.1.7 on 2023-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_newclientcoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='status_coach',
            field=models.CharField(choices=[('recorded', 'Записан'), ('not_recorded', 'Не записан')], default='not_recorded', max_length=255, verbose_name='Статус проверки тренера'),
        ),
    ]
