# Generated by Django 4.1.7 on 2023-03-07 18:43

from django.db import migrations
import django_resized.forms
import project.apps.authorization.models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to=project.apps.authorization.models.path_to_image_profile, verbose_name='Изображение профиля'),
        ),
    ]
