# Generated by Django 4.1.7 on 2023-03-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=255, verbose_name='Направление секции')),
            ],
        ),
        migrations.CreateModel(
            name='SectionYoga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_section', models.CharField(max_length=255, verbose_name='Тип секции')),
                ('type_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.typesection', verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='SectionFighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_section', models.CharField(max_length=255, verbose_name='Тип секции')),
                ('type_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.typesection', verbose_name='Направление')),
            ],
        ),
    ]
