# Generated by Django 4.1.7 on 2023-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_emailactivatetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный'),
        ),
    ]
