# Generated by Django 4.1.7 on 2023-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_typesection_sectionyoga_sectionfighter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_section',
            field=models.CharField(blank=True, choices=[('yoga', 'йога'), ('martialArts', 'единоборства')], default=None, max_length=255, null=True, verbose_name='Тип секции'),
        ),
    ]
